// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "tile":return img`
.................................................
.................................................
.................................................
.................................................
.................................................
.................................................
.....ddddddddddbcbdd.............................
bcbbdd111111111dfbbbbbbd.........................
bcbbbdd11111111dfcccccccccbbdd...................
bcbbbbbbbbbbbbbbfcbbbbbbcccbbbbbbbd...ddddd......
bcbbbbbbcfbcbbbcfccbbbbbccccccccbcc..dbbbbd......
bcbbbbbccfeeeccccccbbcccccbbbbbbbcc..dbbbdb......
bcccccccccccceecccbbbbdbccbbbbbbbcc..deeccc......
bcccccbbccbbbbbccceeeebbbbbbbbdbbcd....b.........
dbccccccccbbbbccccbbebbbebbccccbccdd...b.........
...dbcccccccbbbcccbccbcbbbbbbbbbbbdbbbdb.........
......bccccccccccfcbbbbbbbbbbbbbbbbbbbcbbb.......
......bccccccccccccccbbbbbbbbbbbbbbbbbdbbbbddd...
......bccccccccccccccccbbbbbdbbbbbbbbddddddddddd.
......dccccccccccccccccccbbbbbbbbbbddddddddddddb.
......dccccccccccccccccccccbbbccbbbddddddddddddd.
......dccccccccccccccccccccccccbdddddddddddd.....
.......ccccccccccccccccccccccccbdddd.dddbd.......
.......ddbccccccccccccccffffccccccd..............
...........dcccccccccfffccccbbddd................
..............bccccfccbd.........................
...............dbbd..............................
.................................................
.................................................
.................................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
